#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Nov  2 13:19:45 2019

@author: zcn
"""
imort numpy as np
def discontinuous(poly_array):
    x=[p[0] for p in poly_array]
    y=[p[1] for p in poly_array]
    for i in range():
        a=abs(x[i+1]-x[i])+abs(y[i+1]-y[i])
        if (a==1):
            return 1
        else:
            return 0