#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Nov  1 21:53:48 2019

@author: peterwindsor
"""

#Import Dependencies
import numpy as np
from scipy.spatial import distance as dist

#Polymer Segment Length
l = 1

#Number of Segments
N = 24

#Define Polymer Coordinates
poly_coord = [(n,0) for n in range(0, N, l)]

#Make Polymer Coordinates into Array
poly_array = np.array(poly_coord)

#Calculate Distance Between Each Point
dist_array = dist.cdist(poly_array, poly_array, 'euclidean')

#Print End to End Distance
end_to_end_dist = dist_array[0,N-1]
print(end_to_end_dist)